--- 
title: "NIMBLE User Manual"
author: "NIMBLE Development Team"
date: "Version 0.6-11"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---
Problem is these next items appear after TOC

[https://R-nimble.org](https://R-nimble.org)

[https://github.com/nimble-dev/nimble-docs](https://github.com/nimble-dev/nimble-docs)
<!---
, 'chapter_MCMC.Rmd', 'chapter_OtherAlgorithms.Rmd', 'chapter_Spatial.Rmd', 'chapter_ProgrammingOverview.Rmd', 'chapter_RCfunctions.Rmd', 'chapter_UserDefined.Rmd', 'chapter_UsingModels.Rmd', 'chapter_DataStructures.Rmd', 'chapter_WritingNimbleFunctions.Rmd']
-->

```{r echo=FALSE, include=FALSE}
library(knitr)
library(nimble)
library(methods)
opts_chunk$set(eval = TRUE)
runMCEMs <- FALSE
#version="0.6-11"
```

```{r echo=FALSE, include=FALSE, eval=FALSE}
## for creating combined tables for functions in Writing Models and NF programming
system("cat functionTableLong.md eigenTableMatrix.md > tmp.md")
```
```{r, child = 'tmp.md, eval=FALSE'}
```
```{r echo=FALSE, include=FALSE, eval=FALSE}
system("rm -rf tmp.md")
```


